services:
  mongo:
    image: mongo:8
    container_name: trentino-quest-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: trentino-quest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
