import {
  DailyQuestContext,
  DailyQuestType,
  IDailyQuestDefinition,
} from '../database/models/DailyQuest.model';

export const DAILY_QUEST_POOL: IDailyQuestDefinition[] = [
  // ── In Trentino ──────────────────────────────────────────────────────────
  {
    type: DailyQuestType.WALK_2KM,
    title: 'Camminatore Trentino',
    description: 'Percorri almeno 2 km a piedi esplorando il territorio.',
    context: DailyQuestContext.IN_TRENTINO,
    xpReward: 30,
    coinsReward: 15,
  },
  {
    type: DailyQuestType.FIND_SECONDARY,
    title: 'Cacciatore di Punti',
    description: 'Completa una quest secondaria nelle vicinanze.',
    context: DailyQuestContext.IN_TRENTINO,
    xpReward: 50,
    coinsReward: 20,
  },
  {
    type: DailyQuestType.REACH_ALTITUDE,
    title: 'Scalatore',
    description: 'Raggiungi un punto a oltre 1000 m di quota.',
    context: DailyQuestContext.IN_TRENTINO,
    xpReward: 60,
    coinsReward: 25,
  },
  {
    type: DailyQuestType.LORE_QUIZ,
    title: 'Studioso del Trentino',
    description: 'Rispondi correttamente alla domanda lore del giorno.',
    context: DailyQuestContext.IN_TRENTINO,
    xpReward: 40,
    coinsReward: 20,
  },
  {
    type: DailyQuestType.FLIP_COLLECTIBLES,
    title: 'Collezionista Attivo',
    description: 'Sfoglia 3 collezionabili nel tuo album.',
    context: DailyQuestContext.IN_TRENTINO,
    xpReward: 20,
    coinsReward: 10,
  },
  {
    type: DailyQuestType.SEND_KUDOS,
    title: 'Spirito di Squadra',
    description: 'Invia un kudos a un altro giocatore.',
    context: DailyQuestContext.IN_TRENTINO,
    xpReward: 25,
    coinsReward: 10,
  },
  // ── Fuori regione ─────────────────────────────────────────────────────────
  {
    type: DailyQuestType.WALK_2KM,
    title: 'Esploratore Quotidiano',
    description: 'Cammina 2 km anche fuori dal Trentino.',
    context: DailyQuestContext.OUT_OF_REGION,
    xpReward: 20,
    coinsReward: 10,
  },
  {
    type: DailyQuestType.LORE_QUIZ,
    title: 'Trentino nel Cuore',
    description: 'Rispondi alla domanda di cultura trentina.',
    context: DailyQuestContext.OUT_OF_REGION,
    xpReward: 40,
    coinsReward: 20,
  },
  {
    type: DailyQuestType.FLIP_COLLECTIBLES,
    title: 'Ricordi Trentini',
    description: 'Sfoglia il tuo album e ricorda le avventure.',
    context: DailyQuestContext.OUT_OF_REGION,
    xpReward: 15,
    coinsReward: 8,
  },
  {
    type: DailyQuestType.SEND_KUDOS,
    title: 'Amicizia a Distanza',
    description: 'Mostra supporto a un amico esploratore.',
    context: DailyQuestContext.OUT_OF_REGION,
    xpReward: 20,
    coinsReward: 10,
  },
  {
    type: DailyQuestType.FIND_SECONDARY,
    title: 'Missione Ricordo',
    description: 'Pianifica la prossima quest secondaria da completare.',
    context: DailyQuestContext.OUT_OF_REGION,
    xpReward: 30,
    coinsReward: 15,
  },
  {
    type: DailyQuestType.REACH_ALTITUDE,
    title: 'Sogno di Montagna',
    description: 'Trova un punto panoramico vicino a te (almeno 500 m).',
    context: DailyQuestContext.OUT_OF_REGION,
    xpReward: 25,
    coinsReward: 12,
  },
];
